# Generated by Django 5.2.13 on 2026-08-13 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('reference_id', models.CharField(db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('started', 'Started'), ('completed', 'Completed'), ('approved', 'Approved'), ('declined', 'Declined'), ('failed', 'Failed'), ('expired', 'Expired'), ('needs_review', 'Needs Review')], default='pending', max_length=32)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference_id'], name='kyc_app_per_referen_4a5cf0_idx'), models.Index(fields=['status'], name='kyc_app_per_status_de4891_idx')],
            },
        ),
    ]
